version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - run: echo "hello world"

workflows:
  test-build:
    jobs:
      - build

# VS Code Extension Version: 1.1.1
