#!/bin/sh

# Linting

echo "Checking linting..."

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
unformatted=$(gofmt -l $gofiles)

if [ -n "$unformatted" ]; then
  echo >&2 "Go files must be formatted with gofmt. Please run:"
  for fn in $unformatted; do
    echo >&2 "  gofmt -w $PWD/$fn"
  done
  exit 1
else  
  echo "Linting passed!"
fi

# Secrets detection
echo "Scanning for secrets..."
SECRETS=`detect-secrets scan -n \
    --exclude-files .husky/hooks/pre-commit \
    --exclude-files .circleci/release/release-please-config.json \
    | jq .results`
    
SECRETS_NUMBER=`echo $SECRETS | jq length`

if [ $SECRETS_NUMBER -gt 0 ]; then
    SECRETS_FILE=`echo $SECRETS | jq keys`
    echo "Secrets found in $SECRETS_FILE"
    exit 1
else
    echo "No secrets found!"
    exit 0
fi